trigger:
- none

pool:
  vmImage: ubuntu-latest
  
variables:
- group: k8s-binance-trade-bot

steps: 
  - task: replacetokens@4
    displayName: 'Replace secrets'
    inputs:
      targetFiles: 'k8s/secrets.yml'
      encoding: 'auto'
      tokenPattern: 'default'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      actionOnNoFiles: 'continue'
      enableTransforms: false
      useLegacyPattern: false
      enableTelemetry: true

  - task: KubernetesManifest@0
    displayName: 'Apply manifests'
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'Okteto'
      namespace: 'binance-trade-bot-raschmitt'
      manifests: 'k8s/*.yml'

