apiVersion: v1
kind: Secret
metadata:
  name: user-cfg-secret
type: Opaque
stringData:
  user.cfg: |-
    [binance_user_config]
    api_key=#{BINANCE_API_KEY}#
    api_secret_key=#{BINANCE_API_SECRET_KEY}#
    current_coin=VET
    bridge=USDT
    tld=com
    hourToKeepScoutHistory=1
    scout_multiplier=5
    scout_sleep_time=2
    strategy=multiple_coins
    buy_timeout=0
    sell_timeout=0

---

apiVersion: v1
kind: Secret
metadata:
  name: supported-coin-list-secret
type: Opaque
stringData:
  supported_coin_list: |-
    ADA
    ATOM
    BAT
    BTT
    DASH
    DOGE
    EOS
    ETC
    ICX
    IOTA
    NEO
    OMG
    ONT
    QTUM
    TRX
    VET
    XLM
    XMR

---

apiVersion: v1
kind: Secret
metadata:
  name: apprise-secret
type: Opaque
stringData:
  apprise.yml: |-
    version: 1

    urls:
      - discord://#{DISCORD_WEBHOOK_ID}#/#{DISCORD_WEBHOOK_TOKEN}#/
